# Makes hyprsunset do nothing to the screen by default
# Without this, the default applies some tint to the monitor
profile {
    time = 07:00
    identity = true
}

# Toggle nightlight manually with SUPER + CTRL + N.
# To switch to nightlight automatically, add o.launch_on_start("hyprsunset")
# to the end of ~/.config/hypr/modules/autostart.lua and uncomment:
# profile {
#     time = 20:00
#     temperature = 4000
# }
